version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"
    environment: 
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  kibana:
    image: kibana:6.4.3
    ports:
      - 5601:5601
